# Generated by Django 2.0 on 2017-12-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20171205_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('L', 'Liters'), ('kg', 'kilograms'), ('N', 'number of')], default='N', max_length=2),
        ),
    ]
