# Generated by Django 2.0 on 2017-12-17 17:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20171212_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2017, 12, 17, 17, 10, 13, 43973, tzinfo=utc))),
                ('modified', models.DateTimeField(default=datetime.datetime(2017, 12, 17, 17, 10, 13, 43973, tzinfo=utc))),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('profession', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LabAssistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='product',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='shop',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.AddField(
            model_name='analysis',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Doctor'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='labAssistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.LabAssistant'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Patient'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.AnalysisType'),
        ),
    ]
