# Generated by Django 2.0 on 2017-12-17 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20171217_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
