# Generated by Django 2.0 on 2017-12-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20171217_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='labAssistant',
            new_name='lab_assistant',
        ),
    ]
